# Slicing
---
`arr[start:end:step]` => That's it

_Let's Implement it_

In [ ]:
import numpy as np

# Create an arr of shape (2, 3, 4)
arr = np.array(
    [
        [[1, 2, 3, 4], 
         [2, 5, 3, 5], 
         [3, 88, 22, 12]],
         
        [[4, 33, 22, 88], 
         [123, 44667, 234, 0], 
         [123, 5543, 1145, 332]],
    ]
)

print(arr.shape)

(2, 3, 4)


In [11]:
# Now let's slice
arr1 = arr[0][::-1]
print(arr1)

[[ 3 88 22 12]
 [ 2  5  3  5]
 [ 1  2  3  4]]


### Column Selection
`arr[row, col]` => Select which row, then which column

In [15]:
arr1 = arr[0] # Selecting a single matrix
print("Main Matrix: \n", arr1)
col0 = arr1[:, 0] # [:, 0] => Select all rows, then select their first column
col1 = arr1[:, 1]
col2 = arr1[:, 2]
print(col0)
print(col1)
print(col2)



Main Matrix: 
 [[ 1  2  3  4]
 [ 2  5  3  5]
 [ 3 88 22 12]]
[1 2 3]
[ 2  5 88]
[ 3  3 22]
